apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    categories: Compute
    datasuit: 'Develop, Analysis, Governance'
    icon: https://trino.io/favicon.ico
    capabilities: Basic Install
  name: trino-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Trino is the Schema for the trinoes API
      displayName: Trino
      kind: Trino
      name: trinos.stack.zncdata.net
      version: v1alpha1
  description: trino for k8s operator
  displayName: trino-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - trino
  - k8s
  links:
  - name: Trino Operator
    url: https://trino-operator.domain
  maturity: alpha
  provider:
    name: zncdata-labs
    url: https://github.com/zncdata-labs
  version: 0.0.0
