apiVersion: stack.zncdata.net/v1alpha1
kind: Trino
metadata:
  labels:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino-sample
    app.kubernetes.io/part-of: trino-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trino-operator
  name: trino-sample
spec:
  replicas: 1
  image:
    repository: trinodb/trino
    tag: "423"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  service:
    port: 18080
    type: ClusterIP
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      nginx.ingress.kubernetes.io/rewrite-target: /
    host: trino.example.com
  server:
    node:
      environment: "production"
      dataDir: /data/trino
      pluginDir: /usr/lib/trino/plugin
    config:
      queryMaxMemory: "4GB"
      path: /etc/trino
      https:
        enabled: false
    exchangeManager:
      name: "filesystem"
  coordinator:
    jvm:
      maxHeapSize: "8G"
      gcMethodType: "UseG1GC"
      gcHeapRegionSize: "32M"
    config:
      queryMaxMemoryPerNode: "1GB"
  worker:
    jvm:
      maxHeapSize: "8G"
      gcMethodType: "UseG1GC"
      gcHeapRegionSize: "32M"
    config:
      queryMaxMemoryPerNode: "1GB"
  securityContext:
    runAsUser: 1000
    fsGroup: 1000